lr: 0.001
weight_decay: 0.00001 # l2 norm

max_len: 20

user_id_dim: 64 # not used for SASREC
item_id_dim: 64

embedding_size: 64

decoder_emb_dim: 32
decoder_nhead: 2
aug_label_id_dim: 32
cot_mapping_mlp_hidden_size: [768, 32] 
ICL_history_mlp: [256, 32]
reconstruct_weight: 1.0
aug_dense_feat_dim: 32
