lr: 0.01
weight_decay: 0.0001

max_len: 20

user_id_dim: 32
item_id_dim: 32
item_brand_id_dim: 32
item_cate_id_dim: 32

attention_size: 64
dropout_probs: 0.1
n_layers: 1
num_heads: 2
mlp_hidden_size: [200, 80]
has_residual: True
embedding_size: 32
num_feat_field: 7

teacher_temp: 1
distill_weight: 0.1