lr: 0.01
weight_decay: 0.00001

max_len: 20

user_id_dim: 32
item_id_dim: 32
item_brand_id_dim: 32
item_cate_id_dim: 32

mlp_hidden_size: [200, 80]
cross_layer_num: 3
dropout_prob: 0.1

teacher_temp: 1
distill_weight: 0.1