lr: 0.01
weight_decay: 0.00001

max_len: 20

user_id_dim: 32
item_id_dim: 32
item_brand_id_dim: 32
item_cate_id_dim: 32

mlp_hidden_size: [200, 80]
cross_layer_num: 3
dropout_prob: 0.1

export_num: 4
specific_export_num: 3
convert_arch: [128, 32]
inp_dim: 768
dropout: 0.1