lr: 0.01
weight_decay: 0.0001

max_len: 20

user_id_dim: 32
item_id_dim: 32
item_brand_id_dim: 32
item_cate_id_dim: 32

mixed: True
structure: 'parallel'
cross_layer_num: 2
mlp_hidden_size: [200, 80]
dropout_prob: 0.1
expert_num: 4               # (int) The number of experts in mixed cross network.
low_rank: 4

export_num: 4
specific_export_num: 3
convert_arch: [128, 32]
inp_dim: 768
dropout: 0.1