lr: 0.01
weight_decay: 0.0001

max_len: 20

user_id_dim: 32
item_id_dim: 32
item_brand_id_dim: 32
item_cate_id_dim: 32

attention_size: 64
dropout_probs: 0.1
n_layers: 1
num_heads: 2
mlp_hidden_size: [200, 80]
has_residual: True
embedding_size: 32
num_feat_field: 7

decoder_emb_dim: 32
decoder_nhead: 2
aug_label_id_dim: 32
cot_mapping_mlp_hidden_size: [768, 256, 32] 
ICL_history_mlp: [288, 128, 32]
reconstruct_weight: 0.8

