lr: 0.01
weight_decay: 0.0001
max_len: 20

user_id_dim: 32
item_id_dim: 32
item_brand_id_dim: 32
item_cate_id_dim: 32

hid_units: [200, 80, 1]
dropout: 0.1


export_num: 2
specific_export_num: 3
convert_arch: [128, 32]
inp_dim: 768
dropout: 0.1